jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: pipelines-demo-image
     - TASK: managed

  - name: deploy-pipelines-demo
    type: deploy
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: release-pipelines-demo
    type: release
    steps:
      - IN: pipelines-demo-version
        switch: off
      - IN: deploy-pipelines-demo
        switch: off
      - TASK: managed
        bump: minor
